-- Migration 015: Add ISO 639 language codes table
-- This table stores ISO 639-1 two-letter language codes and their full names

CREATE TABLE IF NOT EXISTS languages (
    code        TEXT PRIMARY KEY,  -- ISO 639-1 two-letter code (e.g., 'en', 'de', 'fr')
    name        TEXT NOT NULL,     -- Full language name (e.g., 'English', 'German', 'French')
    native_name TEXT,              -- Native language name (e.g., 'English', 'Deutsch', 'Français')
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insert ISO 639-1 language codes
-- Source: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
INSERT INTO languages (code, name, native_name) VALUES
('aa', 'Afar', 'Afar'),
('ab', 'Abkhazian', 'Аҧсуа'),
('ae', 'Avestan', 'Avesta'),
('af', 'Afrikaans', 'Afrikaans'),
('ak', 'Akan', 'Akan'),
('am', 'Amharic', 'አማርኛ'),
('an', 'Aragonese', 'Aragonés'),
('ar', 'Arabic', 'العربية'),
('as', 'Assamese', 'অসমীয়া'),
('av', 'Avaric', 'Авар'),
('ay', 'Aymara', 'Aymar'),
('az', 'Azerbaijani', 'Azərbaycan'),
('ba', 'Bashkir', 'Башҡорт'),
('be', 'Belarusian', 'Беларуская'),
('bg', 'Bulgarian', 'Български'),
('bh', 'Bihari languages', 'भोजपुरी'),
('bi', 'Bislama', 'Bislama'),
('bm', 'Bambara', 'Bamanankan'),
('bn', 'Bengali', 'বাংলা'),
('bo', 'Tibetan', 'བོད་ཡིག'),
('br', 'Breton', 'Brezhoneg'),
('bs', 'Bosnian', 'Bosanski'),
('ca', 'Catalan', 'Català'),
('ce', 'Chechen', 'Нохчийн'),
('ch', 'Chamorro', 'Chamoru'),
('co', 'Corsican', 'Corsu'),
('cr', 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ'),
('cs', 'Czech', 'Čeština'),
('cu', 'Church Slavic', 'Словѣньскъ'),
('cv', 'Chuvash', 'Чăваш'),
('cy', 'Welsh', 'Cymraeg'),
('da', 'Danish', 'Dansk'),
('de', 'German', 'Deutsch'),
('dv', 'Divehi', 'ދިވެހި'),
('dz', 'Dzongkha', 'རྫོང་ཁ'),
('ee', 'Ewe', 'Eʋegbe'),
('el', 'Greek', 'Ελληνικά'),
('en', 'English', 'English'),
('eo', 'Esperanto', 'Esperanto'),
('es', 'Spanish', 'Español'),
('et', 'Estonian', 'Eesti'),
('eu', 'Basque', 'Euskara'),
('fa', 'Persian', 'فارسی'),
('ff', 'Fulah', 'Fulfulde'),
('fi', 'Finnish', 'Suomi'),
('fj', 'Fijian', 'Vosa Vakaviti'),
('fo', 'Faroese', 'Føroyskt'),
('fr', 'French', 'Français'),
('fy', 'Western Frisian', 'Frysk'),
('ga', 'Irish', 'Gaeilge'),
('gd', 'Scottish Gaelic', 'Gàidhlig'),
('gl', 'Galician', 'Galego'),
('gn', 'Guarani', 'Avañe''ẽ'),
('gu', 'Gujarati', 'ગુજરાતી'),
('gv', 'Manx', 'Gaelg'),
('ha', 'Hausa', 'Hausa'),
('he', 'Hebrew', 'עברית'),
('hi', 'Hindi', 'हिन्दी'),
('ho', 'Hiri Motu', 'Hiri Motu'),
('hr', 'Croatian', 'Hrvatski'),
('ht', 'Haitian', 'Kreyòl ayisyen'),
('hu', 'Hungarian', 'Magyar'),
('hy', 'Armenian', 'Հայերեն'),
('hz', 'Herero', 'Otjiherero'),
('ia', 'Interlingua', 'Interlingua'),
('id', 'Indonesian', 'Bahasa Indonesia'),
('ie', 'Interlingue', 'Interlingue'),
('ig', 'Igbo', 'Igbo'),
('ii', 'Sichuan Yi', 'ꆈꌠꉙ'),
('ik', 'Inupiaq', 'Iñupiaq'),
('io', 'Ido', 'Ido'),
('is', 'Icelandic', 'Íslenska'),
('it', 'Italian', 'Italiano'),
('iu', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'),
('ja', 'Japanese', '日本語'),
('jv', 'Javanese', 'Basa Jawa'),
('ka', 'Georgian', 'ქართული'),
('kg', 'Kongo', 'Kikongo'),
('ki', 'Kikuyu', 'Gĩkũyũ'),
('kj', 'Kuanyama', 'Kuanyama'),
('kk', 'Kazakh', 'Қазақ'),
('kl', 'Kalaallisut', 'Kalaallisut'),
('km', 'Khmer', 'ភាសាខ្មែរ'),
('kn', 'Kannada', 'ಕನ್ನಡ'),
('ko', 'Korean', '한국어'),
('kr', 'Kanuri', 'Kanuri'),
('ks', 'Kashmiri', 'कश्मीरी'),
('ku', 'Kurdish', 'Kurdî'),
('kv', 'Komi', 'Коми'),
('kw', 'Cornish', 'Kernewek'),
('ky', 'Kirghiz', 'Кыргызча'),
('la', 'Latin', 'Latina'),
('lb', 'Luxembourgish', 'Lëtzebuergesch'),
('lg', 'Ganda', 'Luganda'),
('li', 'Limburgan', 'Limburgs'),
('ln', 'Lingala', 'Lingála'),
('lo', 'Lao', 'ລາວ'),
('lt', 'Lithuanian', 'Lietuvių'),
('lu', 'Luba-Katanga', 'Kiluba'),
('lv', 'Latvian', 'Latviešu'),
('mg', 'Malagasy', 'Malagasy'),
('mh', 'Marshallese', 'Kajin M̧ajeļ'),
('mi', 'Maori', 'Māori'),
('mk', 'Macedonian', 'Македонски'),
('ml', 'Malayalam', 'മലയാളം'),
('mn', 'Mongolian', 'Монгол'),
('mr', 'Marathi', 'मराठी'),
('ms', 'Malay', 'Bahasa Melayu'),
('mt', 'Maltese', 'Malti'),
('my', 'Burmese', 'မြန်မာဘာသာ'),
('na', 'Nauru', 'Dorerin Naoero'),
('nb', 'Norwegian Bokmål', 'Norsk bokmål'),
('nd', 'North Ndebele', 'isiNdebele'),
('ne', 'Nepali', 'नेपाली'),
('ng', 'Ndonga', 'Owambo'),
('nl', 'Dutch', 'Nederlands'),
('nn', 'Norwegian Nynorsk', 'Norsk nynorsk'),
('no', 'Norwegian', 'Norsk'),
('nr', 'South Ndebele', 'isiNdebele'),
('nv', 'Navajo', 'Diné bizaad'),
('ny', 'Chichewa', 'Chichewa'),
('oc', 'Occitan', 'Occitan'),
('oj', 'Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ'),
('om', 'Oromo', 'Afaan Oromoo'),
('or', 'Oriya', 'ଓଡ଼ିଆ'),
('os', 'Ossetian', 'Ирон'),
('pa', 'Punjabi', 'ਪੰਜਾਬੀ'),
('pi', 'Pali', 'पालि'),
('pl', 'Polish', 'Polski'),
('ps', 'Pashto', 'پښتو'),
('pt', 'Portuguese', 'Português'),
('qu', 'Quechua', 'Runa Simi'),
('rm', 'Romansh', 'Rumantsch'),
('rn', 'Rundi', 'Ikirundi'),
('ro', 'Romanian', 'Română'),
('ru', 'Russian', 'Русский'),
('rw', 'Kinyarwanda', 'Kinyarwanda'),
('sa', 'Sanskrit', 'संस्कृतम्'),
('sc', 'Sardinian', 'Sardu'),
('sd', 'Sindhi', 'सिन्धी'),
('se', 'Northern Sami', 'Davvisámegiella'),
('sg', 'Sango', 'Sängö'),
('si', 'Sinhala', 'සිංහල'),
('sk', 'Slovak', 'Slovenčina'),
('sl', 'Slovenian', 'Slovenščina'),
('sm', 'Samoan', 'Gagana Samoa'),
('sn', 'Shona', 'chiShona'),
('so', 'Somali', 'Soomaali'),
('sq', 'Albanian', 'Shqip'),
('sr', 'Serbian', 'Српски'),
('ss', 'Swati', 'SiSwati'),
('st', 'Southern Sotho', 'Sesotho'),
('su', 'Sundanese', 'Basa Sunda'),
('sv', 'Swedish', 'Svenska'),
('sw', 'Swahili', 'Kiswahili'),
('ta', 'Tamil', 'தமிழ்'),
('te', 'Telugu', 'తెలుగు'),
('tg', 'Tajik', 'Тоҷикӣ'),
('th', 'Thai', 'ไทย'),
('ti', 'Tigrinya', 'ትግርኛ'),
('tk', 'Turkmen', 'Türkmençe'),
('tl', 'Tagalog', 'Tagalog'),
('tn', 'Tswana', 'Setswana'),
('to', 'Tonga', 'Lea fakatonga'),
('tr', 'Turkish', 'Türkçe'),
('ts', 'Tsonga', 'Xitsonga'),
('tt', 'Tatar', 'Татарча'),
('tw', 'Twi', 'Twi'),
('ty', 'Tahitian', 'Reo Tahiti'),
('ug', 'Uighur', 'ئۇيغۇرچە'),
('uk', 'Ukrainian', 'Українська'),
('ur', 'Urdu', 'اردو'),
('uz', 'Uzbek', 'Oʻzbek'),
('ve', 'Venda', 'Tshivenḓa'),
('vi', 'Vietnamese', 'Tiếng Việt'),
('vo', 'Volapük', 'Volapük'),
('wa', 'Walloon', 'Walon'),
('wo', 'Wolof', 'Wollof'),
('xh', 'Xhosa', 'isiXhosa'),
('yi', 'Yiddish', 'ייִדיש'),
('yo', 'Yoruba', 'Yorùbá'),
('za', 'Zhuang', 'Saɯ cueŋƅ'),
('zh', 'Chinese', '中文'),
('zu', 'Zulu', 'isiZulu');

-- Create index for faster lookups
CREATE INDEX idx_languages_name ON languages(name);

SELECT 'Migration 015: ISO 639 language codes table created successfully' as message;
